name: Take screenshots

on:
  push:
  workflow_dispatch:
  # Rerun on sunday evenings
  # https://crontab.guru/#0_22_*_*_0
  schedule:
    - cron: "0 22 * * 0"

permissions:
  contents: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'simonw/shot-scraper-template' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    # - uses: actions/github-script@v6
    #   name: Create shots.yml if missing on first run
    #   with:
    #     script: |
    #       const fs = require('fs');
    #       if (!fs.existsSync('shots.yml')) {
    #           const desc = "https://www.strava.com/clubs/129636";
    #           let line = `- url: ${desc}` + '\n  output: shot.png\n  height: 800';
    #           fs.writeFileSync('shots.yml', line + '\n');
    #       }
    # https://www.shell-tips.com/linux/how-to-format-date-and-time-in-linux-macos-and-bash/#gsc.tab=0
    - name: Capture leaderboard data
      run: |
        SHOT_SCRAPER_OUTFILE=$(date +%F_%T)
        shot-scraper javascript https://www.strava.com/clubs/129636 -i download-strava-leaderboard.js -o datasets/$SHOT_SCRAPER_OUTFILE.json
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp} (ci)" || exit 0
        git pull --rebase
        git push
